@startuml analytical dashboard
start
repeat :login; 
:submit;
backward :error;
repeat while (login successful) is (No) not (Yes)
    :redirect to homepage;
    :Click on analytical dashboard;
    end
@enduml